import { open, save } from "@tauri-apps/plugin-dialog";
import { openPath } from "@tauri-apps/plugin-opener";
import {
  cancelPrompt,
  listModels,
  loadSettings,
  respondServerRequest,
  restartAgent,
  runtimeHealth,
  ensureAgentHost,
  agentHostHealth,
  saveSettings,
  sendPrompt,
  setSessionModel,
  setSessionEffort,
  setSessionMode,
  confirmSessionMode,
  setCodingDataPrivacy,
  inspectAttachments,
  prepareAttachments,
  startAgent,
  stopAgent,
  subscribeAcpEvents,
} from "../acp/client";
import {
  createWorktree,
  applyWorktreeChanges,
  appendSessionEvent,
  deleteSession,
  deleteWorktree,
  gitFilePatch,
  gitFileAction,
  gitHunkAction,
  gitCommit,
  gitCreateCheckpoint,
  gitCheckpointRestorePreview,
  gitRestoreCheckpoint,
  workspaceTree,
  workspaceSearch,
  workspaceRead,
  listPolicyRules,
  deletePolicyRule,
  doctorStatus,
  restartAgentHost,
  diagnosticBundlePreview,
  exportDiagnosticBundle,
  gcBlobs,
  rebuildProjections,
  getTask,
  getExecution,
  listExecutionEvents,
  resumeExecution,
  upsertTask,
  listContextManifests,
  saveContextManifest,
  listVerificationResults,
  saveVerificationResult,
  runVerification,
  terminalCreate,
  terminalList,
  terminalOutput,
  terminalPorts,
  terminalInput,
  terminalResize,
  terminalKill,
  terminalRelease,
  taskCompletionGate,
  completeTask,
  exportTranscript,
  gitReview,
  inspectCapabilities,
  listSessions,
  listSessionEvents,
  listWorkspaces,
  listWorktrees,
  previewWorktreeApply,
  saveDraft,
  upsertSession,
  upsertWorkspace,
  installCliOfficial,
  runCliLogin,
  runCliLogout,
  listMcpServers,
  upsertMcpServer,
  removeMcpServer,
  doctorMcpServer,
} from "../api/catalog";
import type { DesktopBridge } from "./DesktopBridge";
import { normalizeCachedEvents } from "../features/shell/history";

export const tauriDesktopBridge: DesktopBridge = {
  kind: "tauri",
  loadSettings,
  saveSettings,
  runtimeHealth,
  ensureAgentHost,
  agentHostHealth,
  installCli: installCliOfficial,
  runLogin: runCliLogin,
  runLogout: runCliLogout,
  subscribeEvents: subscribeAcpEvents,
  listWorkspaces,
  upsertWorkspace,
  listSessions,
  async loadCachedBlocks(sessionId) {
    return normalizeCachedEvents(await listSessionEvents(sessionId));
  },
  appendCachedEvent: appendSessionEvent,
  upsertSession,
  deleteSession,
  saveDraft,
  async chooseDirectory() {
    const result = await open({ directory: true, multiple: false });
    return typeof result === "string" ? result : null;
  },
  async chooseFiles() {
    const result = await open({ directory: false, multiple: true });
    if (!result) return [];
    return (Array.isArray(result) ? result : [result]).filter(
      (item): item is string => typeof item === "string",
    );
  },
  openPath,
  async copyText(text) {
    await navigator.clipboard.writeText(text);
  },
  listModels,
  inspectCapabilities,
  startAgent,
  restartAgent,
  stopAgent,
  sendPrompt,
  cancelPrompt,
  respondServerRequest,
  setSessionModel,
  setSessionEffort,
  setSessionMode,
  confirmSessionMode,
  setCodingDataPrivacy,
  stageAttachments: inspectAttachments,
  prepareAttachments,
  listMcpServers,
  upsertMcpServer,
  removeMcpServer,
  doctorMcpServer,
  gitReview,
  gitFilePatch,
  gitFileAction,
  gitHunkAction,
  gitCommit,
  gitCreateCheckpoint,
  gitCheckpointRestorePreview,
  gitRestoreCheckpoint,
  workspaceTree,
  workspaceSearch,
  workspaceRead,
  listPolicyRules,
  deletePolicyRule,
  doctorStatus,
  restartAgentHost,
  diagnosticBundlePreview,
  async exportDiagnosticBundle() {
    const destination = await save({
      defaultPath: "grok-build-diagnostics.json",
      filters: [{ name: "JSON", extensions: ["json"] }],
    });
    if (!destination) return null;
    return (await exportDiagnosticBundle(destination)).path;
  },
  gcBlobs,
  rebuildProjections,
  getTask,
  getExecution,
  listExecutionEvents,
  resumeExecution,
  upsertTask,
  listContextManifests,
  saveContextManifest,
  listVerificationResults,
  saveVerificationResult,
  runVerification,
  terminalCreate,
  terminalList,
  terminalOutput,
  terminalPorts,
  terminalInput,
  terminalResize,
  terminalKill,
  terminalRelease,
  taskCompletionGate,
  completeTask,
  async exportTranscript(sessionId, format) {
    const extension = format === "json" ? "json" : "md";
    const destination = await save({
      defaultPath: `grok-build-${sessionId}.${extension}`,
      filters: [{ name: format === "json" ? "JSON" : "Markdown", extensions: [extension] }],
    });
    if (!destination) return null;
    const result = await exportTranscript(sessionId, format, destination);
    return result.path;
  },
  listWorktrees,
  createWorktree,
  deleteWorktree,
  previewWorktreeApply,
  applyWorktreeChanges,
};
